baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Authorless'
theme = 'daisy-saas'

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
